### ISSUE TITLE
Cannot run `main_list.dart` example in release

### ISSUE THREAD

**Issue by kirkbyo** [Flutter-Bounty-Hunters/page_list_viewport#8]
When I attempt to run the `main_list.dart` example in release mode I see the following crash. Running the same file in debug works as expected.

```
I/flutter ( 7443): Unsupported operation: Infinity or NaN toInt
I/flutter ( 7443): #0      _Double.~/ (dart:core-patch/double.dart)
I/flutter ( 7443): #1      RenderPageListViewport._findFirstVisiblePageIndex (package:page_list_viewport/src/page_list_viewport.dart:857)
I/flutter ( 7443): #2      RenderPageListViewport._findFirstPaintedPageIndex (package:page_list_viewport/src/page_list_viewport.dart:865)
I/flutter ( 7443): #3      RenderPageListViewport._visitLayoutChildren (package:page_list_viewport/src/page_list_viewport.dart:768)
I/flutter ( 7443): #4      RenderPageListViewport._createAndCullVisibleAndCachedPages.<anonymous closure> (package:page_list_viewport/src/page_list_viewport.dart:726)
I/flutter ( 7443): #5      RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:2300)
I/flutter ( 7443): #6      PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:1056)
I/flutter ( 7443): #7      RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:2300)
I/flutter ( 7443): #8      RenderPageListViewport._createAndCullVisibleAndCachedPages (package:page_list_viewport/src/page_list_viewport.dart:724)
I/flutter ( 7443): #9      RenderPageListViewport.performLayout (package:page_list_viewport/src/page_list_viewport.dart:692)
I/flutter ( 7443): #10     RenderObject.layout (package:flutter/src/rendering/object.dart:2189)
I/flutter ( 7443): #11     RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
I/flutter ( 7443): #12     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120)
I/flutter ( 7443): #13     RenderObject.layout (package:flutter/src/rendering/object.dart:2189)
I/flutter ( 7443): #14     RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
I/flutter ( 7443): #15     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120)
I/flutter ( 7443): #16     RenderObject.layout (package:flutter/src/rendering/object.dart:2189)
I/flutter ( 7443): #17     RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
I/flutter ( 7443): #18     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120)
I/flutter ( 7443): #19     RenderObject.layout (package:flutter/src/rendering/object.dart:2189)
I/flutter ( 7443): #20     RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
I/flutter ( 7443): #21     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171)
I/flutter ( 7443): #22     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1080)
I/flutter ( 7443): #23     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:240)
I/flutter ( 7443): #24     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:410)
I/flutter ( 7443): #25     RenderObject.layout (package:flutter/src/rendering/object.dart:2189)
I/flutter ( 7443): #26     RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
I/flutter ( 7443): #27     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120)
I/flutter ( 7443): #28     RenderObject.layout (package:flutter/src/rendering/object.dart:2189)
I/flutter ( 7443): #29     RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
I/flutter ( 7443): #30     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120)
I/flutter ( 7443): #31     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1467)
I/flutter ( 7443): #32     RenderObject.layout (package:flutter/src/rendering/object.dart:2189)
I/flutter ( 7443): #33     RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
I/flutter ( 7443): #34     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120)
I/flutter ( 7443): #35     RenderObject.layout (package:flutter/src/rendering/object.dart:2189)
I/flutter ( 7443): #36     RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
I/flutter ( 7443): #37     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120)
I/flutter ( 7443): #38     RenderObject.layout (package:flutter/src/rendering/object.dart:2189)
I/flutter ( 7443): #39     RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
I/flutter ( 7443): #40     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120)
I/flutter ( 7443): #41     RenderObject.layout (package:flutter/src/rendering/object.dart:2189)
I/flutter ( 7443): #42     RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
I/flutter ( 7443): #43     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120)
I/flutter ( 7443): #44     RenderObject.layout (package:flutter/src/rendering/object.dart:2189)
I/flutter ( 7443): #45     RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
I/flutter ( 7443): #46     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120)
I/flutter ( 7443): #47     RenderObject.layout (package:flutter/src/rendering/object.dart:2189)
I/flutter ( 7443): #48     RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
I/flutter ( 7443): #49     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120)
I/flutter ( 7443): #50     RenderObject.layout (package:flutter/src/rendering/object.dart:2189)
I/flutter ( 7443): #51     RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
I/flutter ( 7443): #52     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120)
I/flutter ( 7443): #53     RenderObject.layout (package:flutter/src/rendering/object.dart:2189)
I/flutter ( 7443): #54     RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
I/flutter ( 7443): #55     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120)
I/flutter ( 7443): #56     RenderObject.layout (package:flutter/src/rendering/object.dart:2189)
I/flutter ( 7443): #57     RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
I/flutter ( 7443): #58     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120)
I/flutter ( 7443): #59     RenderObject.layout (package:flutter/src/rendering/object.dart:2189)
I/flutter ( 7443): #60     RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
I/flutter ( 7443): #61     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120)
I/flutter ( 7443): #62     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3815)
I/flutter ( 7443): #63     RenderObject.layout (package:flutter/src/rendering/object.dart:2189)
I/flutter ( 7443): #64     RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
I/flutter ( 7443): #65     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120)
I/flutter ( 7443): #66     RenderObject.layout (package:flutter/src/rendering/object.dart:2189)
I/flutter ( 7443): #67     RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
I/flutter ( 7443): #68     _RenderTheatre.performLayout (package:flutter/src/widgets/overlay.dart:856)
I/flutter ( 7443): #69     RenderObject.layout (package:flutter/src/rendering/object.dart:2189)
I/flutter ( 7443): #70     RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
I/flutter ( 7443): #71     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120)
I/flutter ( 7443): #72     RenderObject.layout (package:flutter/src/rendering/object.dart:2189)
I/flutter ( 7443): #73     RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
I/flutter ( 7443): #74     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120)
I/flutter ( 7443): #75     RenderObject.layout (package:flutter/src/rendering/object.dart:2189)
I/flutter ( 7443): #76     RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
I/flutter ( 7443): #77     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120)
I/flutter ( 7443): #78     RenderObject.layout (package:flutter/src/rendering/object.dart:2189)
I/flutter ( 7443): #79     RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
I/flutter ( 7443): #80     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120)
I/flutter ( 7443): #81     RenderObject.layout (package:flutter/src/rendering/object.dart:2189)
I/flutter ( 7443): #82     RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
I/flutter ( 7443): #83     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120)
I/flutter ( 7443): #84     RenderObject.layout (package:flutter/src/rendering/object.dart:2189)
I/flutter ( 7443): #85     RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
I/flutter ( 7443): #86     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120)
I/flutter ( 7443): #87     RenderObject.layout (package:flutter/src/rendering/object.dart:2189)
I/flutter ( 7443): #88     RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
I/flutter ( 7443): #89     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120)
I/flutter ( 7443): #90     RenderObject.layout (package:flutter/src/rendering/object.dart:2189)
I/flutter ( 7443): #91     RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
I/flutter ( 7443): #92     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120)
I/flutter ( 7443): #93     RenderObject.layout (package:flutter/src/rendering/object.dart:2189)
I/flutter ( 7443): #94     RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
I/flutter ( 7443): #95     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120)
I/flutter ( 7443): #96     RenderObject.layout (package:flutter/src/rendering/object.dart:2189)
I/flutter ( 7443): #97     RenderBox.layout (package:flutter/src/rendering/box.dart:2430)
I/flutter ( 7443): #98     RenderView.performLayout (package:flutter/src/rendering/view.dart:175)
I/flutter ( 7443): #99     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2027)
```

**Comment by kirkbyo** [comment]
@matthew-carroll any ideas? Is there a larger problem at play here?
